---
title: "Preprocessament i Modelatge Avançat d'Anàlisi de Dades (PMAAD)"
toc: true
number-sections: true
---

**Preprocessament i models avançats d'anàlisis de dades** és la tercera assignatura d'una seqüència on s'han adquirit ja els rudiments de Probabilitat i Estadística que inclou *Introducció a l'Estadística* (IE, Quadrimestre 2) i els *Models estadístics més bàsics* (ME, Quadrimestre 3). En aquestes assignatures prèvies, l'estudiant de grau de IA ha pogut aprendre nocions bàsiques d'anàlisi exploratòria i descriptiva de dades, teoria de probabilitat i mostreig, nocions d'inferència estadística i disseny d'experiments i models lineals de regressió simple, respectivament. Mentre que, a Modelització estadística, s'introdueix a l'alumne en models més complexos que inclouen, d'una banda, models de classificació, model lineal general i generalitzat i una introducció a sèries temporals com a algorismes supervisats, i, d'altra banda, models no supervisats que inclouen *clustering* i tècniques d'anàlisi multivariant del tipus *PCA.*

En aquesta assignatura es treballarà la metodologia de preprocessament de dades des d'una perspectiva de sistematització del procés i abordatge d'escenaris més complexos, dades composicionals, variables multivaluades, dades multilingües, ... i s'estudiaran mètodes més complexos d'imputació de dades mancants o de diagnòstic i tractament d'outliers que permetin portar la dada a la presa de decisions complexes en aplicacions reals.

Aquesta assignatura integrarà les tècniques més complexes de preprocessament de dades en un escenari genèric de ciència de dades per connectar les dades depurades a models ja sigui d'estadística multivariant, com d'aprenentatge automàtic.

Respecte als mètodes avançats d'anàlisi de dades, es veuran tècniques d'anàlisi multivariant noves, com les que permeten escalar el clustering jeràrquic, noves formes de representar les dades (variables semàntiques) o generalitzen la topologia de classes que es poden reconèixer i l'automatització del postprocessament de dades, que ajuda a interpretar els patron representants en les classes. D'altra banda, s'exploraran diferents tècniques d'estadística multivariant per tractar dades espai-temporals i textuals, així com l'extracció de topics.

[Introducció de l'assignatura](material/2425PresentacioCurs.qmd)

## Advanced Preprocessing

[Introduction and Data Quality](material/01_AdvancedPreprocessing/teoria/Clase1.pdf)

[Missing Data & Feature Engineering](material/01_AdvancedPreprocessing/teoria/Clase2.pdf)

### Automatic Descriptions Analysis (EDA)

[Lab sesion 1 - EDA](material/01_AdvancedPreprocessing/laboratorio/01_automaticEDA.R)

### Outliers Multivariates

[Lab sesion 1 - Outliers Multivariates](material/01_AdvancedPreprocessing/laboratorio/02_deteccioOutliers.R)

  - [Database sesion 1 - Sant Valentin Dates](material/01_AdvancedPreprocessing/laboratorio/valentine_dataset.csv)

### Basic Imputation methods and *MICE/MIMMI/Others*

[Lab sesion 2 - Imputation Methods](material/01_AdvancedPreprocessing/laboratorio/03_01_ImputationMethods.R)

[Lab sesion 2 - MIMMI](material/01_AdvancedPreprocessing/laboratorio/03_02_MIMMI.R)

### Preprocessing Geospacial

[Lab sesion 2 - Preprocessing Geospacial](material/01_AdvancedPreprocessing/laboratorio/04_preproGeoreferencias.R)

## Advanced Clustering

### Times Series Clustering

[Times Series Clustering](material/02_AdvancedClustering/teoria/Time-Series-Clustering.pdf)

[Lab sesion 4 - Times Series Clustering](material/02_AdvancedClustering/laboratorio/05_TimesSeriesClustering.R)

### DBSCAN/OPTICS

[DBSCAN/OPTICS/CURE](material/02_AdvancedClustering/teoria/Clase4.pdf)

[Lab sesion 5 - DBSCAN/OPTICS](material/02_AdvancedClustering/laboratorio/06_DBSCAN-OPTICS.R)

## Advanced Profiling

[Advanced Profiling](material/03_AdvancedProfiling/teoria/Clase5.pdf)

[Lab sesion 6 - TLP, TERMOMETRO, aTLP](material/03_AdvancedProfiling/laboratorio/ProfilingTermometro.zip)

## Correspondence Analysis

### Simple Correspondence Analysis (ACS)

[ACS](material/04_CorrespondenceAnalysis/teoria/Clase6.pdf)

[Lab sesion 7 - ACS](material/04_CorrespondenceAnalysis/laboratorio/ACS.qmd)

### Multiple Correspondence Analysis (ACM) and Factor Analysis of mixed data (FAMD) 

[ACM - FAMD](material/04_CorrespondenceAnalysis/teoria/MCA-FAMD.pdf)

[Lab sesion 8 - ACM/FAMD Script](material/04_CorrespondenceAnalysis/laboratorio/MCA-Example.R)

[Lab sesion 8 - ACM/FAMD Referencia](material/04_CorrespondenceAnalysis/laboratorio/MCA-Example-Ref.pdf)

[Lab sesion 8 - FAMD](material/04_CorrespondenceAnalysis/laboratorio/FAMD.qmd)

## Geospatial Analysis

### Geodescriptiva 

[Geodescriptiva](material/05_GeospatialAnalysis/teoria/geodescriptiva.qmd)

### Geostatatistica  

[Geostatatistica](material/05_GeospatialAnalysis/teoriaGeoestadistica-PMAAD.pdf/)

[Lab sesion 10 - Geostatistica](material/05_GeospatialAnalysis/laboratorio/GeoEstadistica.R)

[Lab sesion 11 - Geomodelling](material/05_GeospatialAnalysis/laboratorio/POINT-Processes-Script.R)

## Texual Analysis

### *CA-GALT* 

[CA-GALT](material/06_TextualAnalysis/teoria/CA-OnTextualData.pdf)

[Textual Analysis](material/06_TextualAnalysis/teoria/PMAAD-TextualAnlysis-Review.pdf)

[Lab sesion 12 - Topic Modelling](material/06_TextualAnalysis/laboratorio/CA-OnTextualData.R)

### *Topic Modelling* 

[Topic Modelling](material/06_TextualAnalysis/teoria/)

[Lab sesion 12 - Topic Modelling](material/06_TextualAnalysis/laboratorio/)

### *Latent Semantic Analysis*

[Latent Semanitc Analysis](material/06_TextualAnalysis/teoria/)

[Lab sesion 13 - LDA](material/06_TextualAnalysis/laboratorio/)
